package meta

import (
	gv "github.com/hashicorp/go-version"
)

const ManifestFile = ".hz"

type Manifest struct {
	Version    string `yaml:"hz version"`
	HandlerDir string `yaml:"handlerDir"`
	ModelDir   string `yaml:"modelDir"`
	RouterDir  string `yaml:"routerDir"`
}

var GoVersion *gv.Version

func init() {

	GoVersion, _ = gv.NewVersion(Version)
}

func (manifest *Manifest) InitAndValidate(dir string) error { _ = "STUB: not implemented"; return nil }

const hzTitle = "// Code generated by hz. DO NOT EDIT."

func (manifest *Manifest) String() string { _ = "STUB: not implemented"; return "" }

func (manifest *Manifest) Persist(dir string) error { _ = "STUB: not implemented"; return nil }

func loadConfigFile(path string) (*Manifest, error) { _ = "STUB: not implemented"; return nil, nil }
